 export const ActionsTypes = {
     SET_MOVIES : "SET_MOVIES",
     GET_MOVIE : "GET_MOVIE", 
     REMOVE_MOVIE : "REMOVE_MOVIE",
     QUANTITY: "QUANTITY",
     TOTAL_MONEY : "TOTAL_MONEY",
     ADD_PRODUCT : "ADD_PRODUCT",
 }